# Generated by Django 5.2.7 on 2025-10-23 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('sell_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('trade_amount', models.DecimalField(decimal_places=6, default=0.001, max_digits=10)),
                ('stop_loss_enabled', models.BooleanField(default=True)),
                ('stop_loss_pct', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('trailing_stop_enabled', models.BooleanField(default=False)),
                ('trailing_stop_pct', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(default='BTC/USDT', max_length=20)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('profit_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss')], max_length=4, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
